# Generated by Django 2.0b1 on 2017-11-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='https://www.youtube.com'),
            preserve_default=False,
        ),
    ]
