# Generated by Django 2.0b1 on 2017-11-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171116_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='htmlname',
        ),
    ]
