# Generated by Django 2.0b1 on 2017-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_article_htmlname'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='htmlname',
            field=models.CharField(default='adaptivegrain', max_length=255),
            preserve_default=False,
        ),
    ]
